#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts none /dev/pts
mkdir /mnt
mount -o nolock,rsize=1024 192.168.220.1:/srv/home /mnt
ifconfig lo 127.0.0.1
# ifconfig eth0 172.17.0.199


